/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.home.weatherstation;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void test() {
        String s = new String("a");
        assertNotNull(s, "Should not be null");
    }
}
